### ISSUE TITLE
Working With Fragment

### ISSUE THREAD

**Issue by arashifunsho** [nguyenhoanglam/ImagePicker#30]
I have issues using this library with fragments. The result isn't returned even though the host activity has a 

`super.onActivityResult(requestCode, resultCode, data);`

in it's onActivityResult method which is also overrode in the fragment to do the necessary manipulation

Please help

**Comment by nguyenhoanglam** [comment]
You're right! In this case, the bug occurs when you use _**quick call**_ to start picker activity. The _**onActivityResult**_ method not called in fragment but in activity.
To avoid this problem, please call picker using intent. Note that you have to use:
```java
startActivityForResult(intent, REQUEST_CODE);
```
instead of 
```java
getActivity().startActivityForResult(intent, REQUEST_CODE);
```
I'll fix this bug in the next version.
Thanks for you report!

**Comment by arashifunsho** [comment]
Awesome... Thank You.... I totally forgot there were two ways stated in the Readme would have tried the other one..

Cheers Bro.... Keep up the good work..
