### ISSUE TITLE
It gives error after take photo by camera for some devices

### ISSUE THREAD

**Issue by gcatak** [nguyenhoanglam/ImagePicker#47]
According to user feedback, it gives error after take photo by camera. Then, how to solve? 
In my smartphone, there is no problem camera is working properly. So no logcat but for some smartphones it gives error. How to solve?

**Comment by edindubai** [comment]
It crashes the Samsung S4 Mini camera after taking the photo in 1.1.3 android version 4.2.2. The picture arrives in the gallery though but only after "Unfortunately, Camera has stopped" message, it is a guaranteed crash on every try. (works ok on S6 edge)

On another matter is it possible to return to the open camera folder after taking the photo rather than the front page with all the other image folders? As it stands now you have to then click back into the camera folder in order to then select the image, why add the extra step?

Thanks

**Comment by edindubai** [comment]
This version seems to not crash https://android-arsenal.com/details/1/4618

**Comment by Rainer-Lang** [comment]
@gcatak @edindubai Are you using the newest version? Please test it - maybe this issue could be closed.

**Comment by yolao** [comment]
It crashes the Samsung S4 Mini camera after taking the photo

**Comment by Rainer-Lang** [comment]
@yolao Could you please try v1.2.1? Maybe you could post the log.

**Comment by nguyenhoanglam** [comment]
Hi guys,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!
