### ISSUE TITLE
Difference to another lib...

### ISSUE THREAD

**Issue by Rainer-Lang** [nguyenhoanglam/ImagePicker#66]
I don't know what's the difference between your lib and this one: https://github.com/esafirm/android-image-picker
Maybe you could clarify a bit...

**Comment by nguyenhoanglam** [comment]
Initially, esafirm had forked my lib (ver 1.1.x) and implemented code style (MVP pattern, helpers class...). Because my old lib had some issues that I can not fixed, so I reused esafirm's code. 

There are two differences between my lib to esafirm's lib are:
- Redesign UI
- Provide more additional ways to customize UI
- Customize CameraOnly mode for convenient to use
- Implement Glide v4

**Comment by Rainer-Lang** [comment]
Thank you very much!

I'm using the esafirm lib - but the missing Glide v4 support isn't very "nice"....

Suggestion:
In ImagePicker-builder: use resource-ids for strings and even colors.  Then you also could use Support Annotations.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Is it possible to include resource-ids in build with the next version? I don't want to convert my resource id strings or colors to strings... I would be a lot of effort. What do you think?

**Comment by nguyenhoanglam** [comment]
I'll try to meet you expectation. It's good advice!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I really appreciate your work! I prepare now all to include your lib. But take your time.

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang I'm so happy when you use and support my lib. It give me a motivation to make this lib more useful.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam It's already useful and great! :-)
